Repository WildCodeSchool/reims-0218-artezicreloaded, pull requests merged in 2018-05, with the labels that each got.

#39 User can vote
  auth.js
  passport-strategy.js
  public/app.js
  public/style.css
  public/utils.js
  server.js
Labels: enhancement, improvement

#40 fix: CORRECT eventlistener for modal that was misplaced.
  public/app.js
Labels: bug, fix

#42 Css equipe
  public/app.js
  public/style.css
  server.js
Labels: enhancement

#43 Navbar style active links2
  public/app.js
  server.js
Labels: enhancement

#44 resolve minor bugs on the profile
  public/app.js
Labels: enhancement

#47 Database debug
  migrations/001-create-users-table.sql
  public/user-playlists.json
  server.js
Labels: fix

#48 Arnaud bugs corrections
  public/app.js
Labels: enhancement

#51 Qaf
  public/app.js
  public/style.css
  server.js
Labels: enhancement

#52 Fix thibaud
  public/app.js
  public/style.css
Labels: enhancement
