Repository WildCodeSchool/reims-0218-artezicreloaded, pull requests merged in 2018-04, with the labels that each got.

#6 Description and contributing paragraphs
  README.md
Labels: documentation, setup

#7 test route member
  public/user-playlists.json
  server.js
Labels: build

#9 New feature: Navbar
  .gitignore
  migrations/001-create-users-table.sql
  package-lock.json
  package.json
  public/app.js
  public/team.json
  server.js
Labels: enhancement

#14 bout de code retrouvé !
  public/app.js
Labels: enhancement

#17 Gontran displays his playlists
  migrations/001-create-users-table.sql
  package-lock.json
  package.json
  playlists.js
  public/app.js
  public/our-functions.js
  public/playlists-by-wilders.js
  public/test-run.js
  public/test-setup.js
  public/test.html
  public/test.js
  public/user-playlists.json
  server.js
  test/playlists.test.js
  test/test.js
Labels: enhancement

#20 Display winning playlist
  public/app.js
  server.js
Labels: enhancement

#21 Debug displays for all wilders
  migrations/001-create-users-table.sql
  public/app.js
  public/our-functions.js
  public/playlists-by-wilders.js
  public/test-run.js
  public/test-setup.js
  public/test.html
  public/test.js
  server.js
  test/test.js
Labels: enhancement

#25 Display playlist content in modal
  migrations/001-create-users-table.sql
  public/app.js
  server.js
Labels: enhancement

#30 User can upload img
  public/app.js
  public/user-playlists.json
  server.js
Labels: enhancement

#32 Modify playlists url in db
  migrations/001-create-users-table.sql
  public/app.js
  server.js
Labels: fix

#34 Improve playlists modal
  migrations/001-create-users-table.sql
  public/app.js
  public/user-playlists.json
  server.js
Labels: fix

#37 See all playlists in /
  public/app.js
Labels: improvement
